# Generated by Django 3.2.4 on 2021-07-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trips_stops",
            old_name="stop_id",
            new_name="stop",
        ),
        migrations.RenameField(
            model_name="trips_stops",
            old_name="trip_id",
            new_name="trip",
        ),
    ]
