# Generated by Django 3.2.4 on 2021-07-05 15:26

from django.db import migrations

import csv


def insert_routes_data(apps, schema_editor):
    Route = apps.get_model("main", "Route")
    with open("./main/migrations/final_routes_csv.csv") as routes_csv:
        csv_reader = csv.reader(routes_csv, delimiter=",")
        next(csv_reader)
        for row in csv_reader:
            route = Route(id=row[0], short_name=row[1])
            route.save()


def insert_trips_data(apps, schema_editor):
    Trip = apps.get_model("main", "Trip")
    with open("./main/migrations/final_trips_csv.csv") as trips_csv:
        csv_reader = csv.reader(trips_csv, delimiter=",")
        next(csv_reader)
        for row in csv_reader:
            trip = Trip(id=row[1], route_id=row[0], headsign=row[2])
            trip.save()


def insert_trips_and_stops_data(apps, schema_editor):
    Stop = apps.get_model("main", "Stop")
    Trips_Stops = apps.get_model("main", "Trips_Stops")
    stops_added = {}
    with open("./main/migrations/final_stops_trips_csv.csv") as stops_trips_csv:
        csv_reader = csv.reader(stops_trips_csv, delimiter=",")
        next(csv_reader)
        for row in csv_reader:
            if row[0] not in stops_added:
                stop = Stop(id=row[0], name=row[1], latitude=row[2], longitude=row[3])
                stop.save()
                stops_added[row[0]] = 1
            trip_stop = Trips_Stops(trip_id=row[4], stop_id=row[0])
            trip_stop.save()


def insert_data_in_db(apps, schema_editor):
    insert_routes_data(apps, schema_editor)
    insert_trips_data(apps, schema_editor)
    insert_trips_and_stops_data(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210705_1748"),
    ]

    operations = [migrations.RunPython(insert_data_in_db)]
