# Generated by Django 3.2.4 on 2021-07-27 10:11

from django.db import migrations
from main.models import Route, Trip, Trips_Stops, Stop


def delete_routes(apps, schema_editor):
    all_routes = Route.objects.all()
    route_dict = {}

    print("Routes in db before deletions")
    for route in all_routes:
        print(f"route: {route.short_name}")
        if route.short_name not in route_dict:
            route_dict[route.short_name] = False
        trips = Trip.objects.filter(route_id=route.id).order_by("id")[:2]
        if trips:
            for trip in trips:
                stops = Trips_Stops.objects.filter(trip_id=trip.id)
                if stops:
                    route_dict[route.short_name] = True

    for key in route_dict.keys():
        if route_dict[key] == False:
            Route.objects.filter(short_name=key).delete()
            print(f"{key} route was deleted")

    all_routes_after_deletions = Route.objects.all()
    print("Routes in db after deletions")
    for route in all_routes_after_deletions:
        print(f"route: {route.short_name}")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210705_1748"),
    ]

    operations = [migrations.RunPython(delete_routes)]
