# Generated by Django 3.2.4 on 2021-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210727_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50)),
                ('arrival_time', models.TimeField()),
                ('stop_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stop_times',
            },
        ),
    ]
