# Generated by Django 3.2.4 on 2021-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20210727_1111"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop_Times",
            fields=[
                ("trip_id", models.CharField(max_length=50)),
                ("arrival_time", models.TimeField()),
                ("stop_id", models.CharField(max_length=50)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "stop_times",
            },
        ),
    ]
