# Generated by Django 3.2.4 on 2021-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_stop_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="trips_stops",
            name="progress_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
