# Generated by Django 3.2.4 on 2021-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_trips_stops_progress_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="direction",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
