# Generated by Django 3.2.4 on 2021-08-10 18:42

from django.db import migrations
from main.models import Route

# there's a route with id 60-33D-b12-1 in the database that incorrectly has the name 33b
# this function updates the short_name field to 33d
def rename_route_33d(apps, schema_editor):
    Route.objects.filter(id="60-33D-b12-1").update(short_name="33d")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_trip_direction"),
    ]

    operations = [migrations.RunPython(rename_route_33d)]
