# Generated by Django 3.2.4 on 2021-08-10 19:15

from django.db import migrations
from main.models import Route

# route 33b has no trips that's why we are deleting
def delete_route_33b(apps, schema_editor):
    Route.objects.filter(short_name="33b").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_route_33d"),
    ]

    operations = [migrations.RunPython(delete_route_33b)]
