name: Coverage CI steps

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6.51
        env:
          MYSQL_DATABASE: dublin_bus
          MYSQL_ROOT_PASSWORD: ${{ secrets.DEVELOPMENT_DATABASE_PASSWORD }}
        ports:
          - 3306:3306

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Install requirements and coverage.py
      - name: Install required dependencies
        run: pip install -r dublinbus/requirements.txt && pip install coverage
      # Run coverage
      - name: Run coverage
        run: cd dublinbus && coverage run --source='.' manage.py test main
        env:
          WEATHER_APIKEY: ${{ secrets.WEATHER_APIKEY }}
          GOOGLEMAPS_APIKEY: ${{ secrets.GOOGLEMAPS_APIKEY }}
          DEVELOPMENT_DATABASE_USER: ${{ secrets.DEVELOPMENT_DATABASE_USER }}
          DEVELOPMENT_DATABASE_PASSWORD: ${{ secrets.DEVELOPMENT_DATABASE_PASSWORD }}
          DEVELOPMENT_DATABASE_HOST: ${{ secrets.DEVELOPMENT_DATABASE_HOST }}
          DEVELOPMENT_DATABASE_PORT: ${{ secrets.DEVELOPMENT_DATABASE_PORT }}
          MYSQL_HOST: mysql

      # Get coverage report
      - name: Run coverage.py report
        run: cd dublinbus && coverage report
