name: Django CI steps

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6.51
        env:
          MYSQL_DATABASE: dublin_bus
          MYSQL_ROOT_PASSWORD: ${{ secrets.DEVELOPMENT_DATABASE_PASSWORD }}
        ports:
          - 3306:3306

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Install all required dependencies
      - name: Install dependencies
        run: pip install -r dublinbus/requirements.txt
      # --check returns 0 if there's no modifications needed or 1 if there's linting issues
      - name: Run black --check .
        run: black --check .          
      # Execute all Django tests
      - name: Run Django tests
        run: cd dublinbus && python manage.py test
        env:
          GOOGLEMAPS_APIKEY: ${{ secrets.GOOGLEMAPS_APIKEY }}
          DEVELOPMENT_DATABASE_USER: ${{ secrets.DEVELOPMENT_DATABASE_USER }}
          DEVELOPMENT_DATABASE_PASSWORD: ${{ secrets.DEVELOPMENT_DATABASE_PASSWORD }}
          DEVELOPMENT_DATABASE_HOST: ${{ secrets.DEVELOPMENT_DATABASE_HOST }}
          DEVELOPMENT_DATABASE_PORT: ${{ secrets.DEVELOPMENT_DATABASE_PORT }}
