name: Frontend CI steps

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up Node v14
      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      # Installs prettier version 2.2.1 to match the version we have locally, otherwise npm will always install the latest and CI can break
      - name: Install prettier
        run: npm install -g prettier@2.2.1
      # --check returns 0 if there's no modifications needed or 1 if there's linting issues
      - name: Run prettier --check .
        run: cd dublinbus && prettier --check .
